### ISSUE TITLE
Name resolution error upon installing phpipam

### ISSUE THREAD

**Issue by Haribo112** [natesubra/phpipam-docker#2]
Hi. After using your docker-compose file to spin up the containers, I go to the web page of the phpipam instance. I am then asked to install phpipam, but it fails on creating the MySQL database:

Could not connect to database! SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

The field 'database location' contains the text 'phpipam_mysql_1' and cannot be changed. How did you resolve this? Did you create the database manually?
![2018-07-10 11_34_02-phpipam installation](https://user-images.githubusercontent.com/4678943/42501965-2e94c696-8435-11e8-9ebf-54f30b20e6f0.png)

**Comment by natesubra** [comment]
this can be fixed by setting the container name in the compose file, I've updated the reference yml.
