### ISSUE TITLE
Wrong image name in docker compose

### ISSUE THREAD

**Issue by eranyo** [natesubra/phpipam-docker#3]
Hi , 
You have a mistake in the image name 
its shows  scrubs/phpipam:latest while the right image name is     image: scrubs/phpipam-docker :latest

**Comment by natesubra** [comment]
Thank you! I'll have a fix up shortly

**Comment by natesubra** [comment]
https://github.com/natesubra/phpipam-docker/commit/d504abdb118c32684db2e6c871e028741d25801b
